import { WaveformEngine } from './waveform';
import type { Summary } from './stats';

export interface ExportOptions {
  engine: WaveformEngine;
  presetText: string;
  summary: Summary;
  when: Date;
}

const WIDTH = 1280;
const HEIGHT = 760;

function fmtTime(ms: number): string {
  const totalSeconds = ms / 1000;
  const m = Math.floor(totalSeconds / 60);
  const s = (totalSeconds % 60).toFixed(2);
  return `${m}:${s.padStart(5, '0')}`;
}

function fmtDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return (
    `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ` +
    `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
  );
}

/** Renders the confirmed waveform + stats onto an offscreen canvas as a
 * "monitor printout" style image, styled after the live CRT screen. */
export function renderExportCanvas(opts: ExportOptions): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  const dpr = Math.min(2, window.devicePixelRatio || 1);
  canvas.width = WIDTH * dpr;
  canvas.height = HEIGHT * dpr;
  const ctx = canvas.getContext('2d');
  if (!ctx) throw new Error('canvas 2d context unavailable');
  ctx.scale(dpr, dpr);

  // Chassis background.
  ctx.fillStyle = '#04100a';
  ctx.fillRect(0, 0, WIDTH, HEIGHT);

  // Outer bezel frame.
  ctx.strokeStyle = '#123322';
  ctx.lineWidth = 10;
  ctx.strokeRect(5, 5, WIDTH - 10, HEIGHT - 10);

  // Header block.
  ctx.fillStyle = '#39ff88';
  ctx.font = '700 26px "JetBrains Mono", monospace';
  ctx.textBaseline = 'alphabetic';
  ctx.fillText('TYPING EKG — PATIENT READOUT', 40, 56);

  ctx.font = '400 16px "JetBrains Mono", monospace';
  ctx.fillStyle = '#6fae86';
  const dateStr = fmtDate(opts.when);
  const dateWidth = ctx.measureText(dateStr).width;
  ctx.fillText(dateStr, WIDTH - 40 - dateWidth, 56);

  // Divider.
  ctx.strokeStyle = 'rgba(57, 255, 136, 0.25)';
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.moveTo(40, 74);
  ctx.lineTo(WIDTH - 40, 74);
  ctx.stroke();

  // Sentence label (wraps if long).
  ctx.font = '500 18px "JetBrains Mono", monospace';
  ctx.fillStyle = '#c8ffe0';
  const label = `TEXT:  ${opts.presetText}`;
  wrapText(ctx, label, 40, 104, WIDTH - 80, 24);

  // Waveform panel.
  const panel = { x: 40, y: 150, width: WIDTH - 80, height: 380 };
  ctx.save();
  ctx.fillStyle = '#010a06';
  ctx.fillRect(panel.x, panel.y, panel.width, panel.height);
  ctx.strokeStyle = 'rgba(57, 255, 136, 0.35)';
  ctx.lineWidth = 2;
  ctx.strokeRect(panel.x + 1, panel.y + 1, panel.width - 2, panel.height - 2);
  ctx.beginPath();
  ctx.rect(panel.x, panel.y, panel.width, panel.height);
  ctx.clip();

  opts.engine.drawGrid(ctx, panel.x + panel.width, panel.y + panel.height, 24);

  const beats = opts.engine.getBeats();
  const lastT = beats.length > 0 ? beats[beats.length - 1]!.t : 1000;
  opts.engine.drawTrace(
    ctx,
    { timeStart: 0, timeEnd: Math.max(1200, lastT + 400) },
    panel,
    { glow: true },
  );
  ctx.restore();

  // Stats strip.
  const stats: Array<[string, string]> = [
    ['ELAPSED', fmtTime(opts.summary.elapsedMs)],
    ['CPM', String(opts.summary.cpm)],
    ['WPM', String(opts.summary.wpm)],
    ['IRREGULARITY', `${opts.summary.irregularityScore}`],
    ['BACKSPACES', String(opts.summary.backspaceCount)],
  ];
  const stripY = panel.y + panel.height + 36;
  const cellWidth = panel.width / stats.length;
  stats.forEach(([label, value], i) => {
    const cx = panel.x + cellWidth * i;
    if (i > 0) {
      ctx.strokeStyle = 'rgba(57, 255, 136, 0.2)';
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(cx, stripY - 30);
      ctx.lineTo(cx, stripY + 20);
      ctx.stroke();
    }
    ctx.font = '600 12px "JetBrains Mono", monospace';
    ctx.fillStyle = '#6fae86';
    ctx.fillText(label, cx + 18, stripY - 8);
    ctx.font = '700 30px "JetBrains Mono", monospace';
    ctx.fillStyle =
      label === 'IRREGULARITY' && opts.summary.irregularityScore > 55
        ? '#ffb454'
        : '#39ff88';
    ctx.fillText(value, cx + 18, stripY + 20);
  });

  // Footer stamp.
  ctx.font = '400 13px "JetBrains Mono", monospace';
  ctx.fillStyle = '#3d6b52';
  ctx.fillText(
    'GENERATED BY TYPING EKG — apps/typing-ekg (app-factory prototype)',
    40,
    HEIGHT - 26,
  );

  return canvas;
}

function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): void {
  const words = text.split(' ');
  let line = '';
  let cy = y;
  for (const word of words) {
    const test = line.length > 0 ? `${line} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && line.length > 0) {
      ctx.fillText(line, x, cy);
      line = word;
      cy += lineHeight;
    } else {
      line = test;
    }
  }
  if (line.length > 0) ctx.fillText(line, x, cy);
}

export async function downloadExportPng(opts: ExportOptions): Promise<void> {
  const canvas = renderExportCanvas(opts);
  const blob: Blob | null = await new Promise((resolve) =>
    canvas.toBlob(resolve, 'image/png'),
  );
  if (!blob) throw new Error('failed to encode PNG');

  const pad = (n: number) => String(n).padStart(2, '0');
  const d = opts.when;
  const filename =
    `typing-ekg_${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}` +
    `_${pad(d.getHours())}${pad(d.getMinutes())}${pad(d.getSeconds())}.png`;

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
