import type { Point, VesselId } from './types';

/**
 * Each vessel is defined as a closed region built from cubic bezier curves.
 * Only the right-hand half profile (from the rim down to the bottom center)
 * is authored; the left half is generated by mirroring, and the rim is
 * closed with a symmetric dip curve suggesting the far edge of the opening.
 * All coordinates are in the vessel's own local space: x is an offset from
 * the vertical center axis (positive = right), y grows downward from the
 * rim. This local space is also what crack generation operates in, so
 * cracks never need to know about on-screen pixel scale.
 */
interface RightProfileSeg {
  c1x: number;
  c1y: number;
  c2x: number;
  c2y: number;
  x: number;
  y: number;
}

export interface VesselSpec {
  id: VesselId;
  label: string;
  topHalfWidth: number;
  topY: number;
  /** Control point offset/height used to close the rim curve across the top. */
  rimDipX: number;
  rimDipY: number;
  rightProfile: RightProfileSeg[];
}

export const VESSELS: Record<VesselId, VesselSpec> = {
  bowl: {
    id: 'bowl',
    label: '碗',
    topHalfWidth: 140,
    topY: 60,
    rimDipX: 55,
    rimDipY: 80,
    rightProfile: [
      // Segment 1: rim down to the widest point of the belly.
      { c1x: 148, c1y: 95, c2x: 152, c2y: 145, x: 150, y: 190 },
      // Segment 2: a quarter-ellipse (bezier kappa ~0.552) from the belly to
      // the bottom center. Its second control point shares the endpoint's y,
      // giving a horizontal tangent at the seam where the mirrored left/right
      // halves meet — without this the bottom renders as a pointed cusp
      // instead of a smoothly rounded base.
      { c1x: 150, c1y: 262, c2x: 83, c2y: 320, x: 0, y: 320 },
    ],
  },
  plate: {
    id: 'plate',
    label: '皿',
    topHalfWidth: 185,
    topY: 112,
    rimDipX: 92,
    rimDipY: 152,
    rightProfile: [
      { c1x: 201, c1y: 132, c2x: 206, c2y: 157, x: 196, y: 176 },
      { c1x: 186, c1y: 200, c2x: 140, c2y: 230, x: 70, y: 246 },
      { c1x: 45, c1y: 251, c2x: 20, c2y: 253, x: 0, y: 253 },
    ],
  },
  vase: {
    id: 'vase',
    label: '花瓶',
    topHalfWidth: 44,
    topY: 30,
    rimDipX: 20,
    rimDipY: 44,
    rightProfile: [
      { c1x: 50, c1y: 55, c2x: 53, c2y: 76, x: 48, y: 96 },
      { c1x: 60, c1y: 122, c2x: 120, c2y: 142, x: 155, y: 190 },
      { c1x: 166, c1y: 230, c2x: 161, c2y: 281, x: 130, y: 330 },
      { c1x: 105, c1y: 361, c2x: 70, c2y: 386, x: 35, y: 400 },
      { c1x: 20, c1y: 408, c2x: 10, c2y: 410, x: 0, y: 410 },
    ],
  },
};

export const VESSEL_ORDER: VesselId[] = ['bowl', 'plate', 'vase'];

export interface VesselBounds {
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
  width: number;
  height: number;
  midY: number;
}

const boundsCache = new Map<VesselId, VesselBounds>();

/**
 * Cubic bezier curves stay within the convex hull of their control points,
 * so scanning start/control/end points of every segment yields a safe
 * (if slightly generous) bounding box without sampling the curve itself.
 */
export function getBounds(spec: VesselSpec): VesselBounds {
  const cached = boundsCache.get(spec.id);
  if (cached) return cached;

  let maxX = spec.topHalfWidth;
  let minY = spec.topY;
  let maxY = spec.topY;

  const consider = (x: number, y: number): void => {
    if (Math.abs(x) > maxX) maxX = Math.abs(x);
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  };

  for (const seg of spec.rightProfile) {
    consider(seg.c1x, seg.c1y);
    consider(seg.c2x, seg.c2y);
    consider(seg.x, seg.y);
  }
  consider(spec.rimDipX, spec.rimDipY);

  const bounds: VesselBounds = {
    minX: -maxX,
    maxX,
    minY,
    maxY,
    width: maxX * 2,
    height: maxY - minY,
    midY: (minY + maxY) / 2,
  };
  boundsCache.set(spec.id, bounds);
  return bounds;
}

export interface VesselTransform {
  cx: number;
  cy: number;
  scale: number;
}

/** Fits the vessel's own bounding box into the given canvas area. */
export function computeTransform(
  canvasW: number,
  canvasH: number,
  spec: VesselSpec,
  fill = 0.78,
): VesselTransform {
  const bounds = getBounds(spec);
  const scale = Math.min((canvasW * fill) / bounds.width, (canvasH * fill) / bounds.height);
  return { cx: canvasW / 2, cy: canvasH / 2, scale };
}

export function toCanvasPoint(p: Point, t: VesselTransform, bounds: VesselBounds): Point {
  return { x: t.cx + p.x * t.scale, y: t.cy + (p.y - bounds.midY) * t.scale };
}

/** Generic builder: mapX/mapY convert local vessel coordinates into whatever
 * target space is needed (raw local space for hit-testing, or canvas pixel
 * space for drawing). Sharing this keeps the two paths perfectly consistent. */
function buildOutline(spec: VesselSpec, mapX: (x: number) => number, mapY: (y: number) => number): Path2D {
  const path = new Path2D();
  path.moveTo(mapX(spec.topHalfWidth), mapY(spec.topY));
  for (const seg of spec.rightProfile) {
    path.bezierCurveTo(mapX(seg.c1x), mapY(seg.c1y), mapX(seg.c2x), mapY(seg.c2y), mapX(seg.x), mapY(seg.y));
  }
  const n = spec.rightProfile.length;
  for (let i = n - 1; i >= 0; i--) {
    const seg = spec.rightProfile[i]!;
    const prevSeg = i > 0 ? spec.rightProfile[i - 1]! : null;
    const endX = prevSeg ? -prevSeg.x : -spec.topHalfWidth;
    const endY = prevSeg ? prevSeg.y : spec.topY;
    path.bezierCurveTo(mapX(-seg.c2x), mapY(seg.c2y), mapX(-seg.c1x), mapY(seg.c1y), mapX(endX), mapY(endY));
  }
  path.bezierCurveTo(
    mapX(-spec.rimDipX),
    mapY(spec.rimDipY),
    mapX(spec.rimDipX),
    mapY(spec.rimDipY),
    mapX(spec.topHalfWidth),
    mapY(spec.topY),
  );
  path.closePath();
  return path;
}

/** Path2D in canvas pixel space, ready to fill/stroke/clip on screen. */
export function buildCanvasPath(spec: VesselSpec, t: VesselTransform): Path2D {
  const bounds = getBounds(spec);
  return buildOutline(
    spec,
    (x) => t.cx + x * t.scale,
    (y) => t.cy + (y - bounds.midY) * t.scale,
  );
}

const containCache = new Map<VesselId, Path2D>();
const hitCache = new Map<VesselId, Path2D>();

/** Exact silhouette in local space, used to keep generated cracks inside the vessel. */
export function getContainPath(spec: VesselSpec): Path2D {
  let path = containCache.get(spec.id);
  if (!path) {
    path = buildOutline(
      spec,
      (x) => x,
      (y) => y,
    );
    containCache.set(spec.id, path);
  }
  return path;
}

/** Slightly enlarged silhouette (in local space) used only for pointer hit
 * testing, so mobile taps near the edge still register (per requirements). */
export function getHitPath(spec: VesselSpec): Path2D {
  let path = hitCache.get(spec.id);
  if (!path) {
    const bounds = getBounds(spec);
    const expand = 1.09;
    path = buildOutline(
      spec,
      (x) => x * expand,
      (y) => bounds.midY + (y - bounds.midY) * expand,
    );
    hitCache.set(spec.id, path);
  }
  return path;
}

// A detached 1x1 canvas used purely for Path2D geometry queries
// (isPointInPath does not depend on the canvas's actual pixel size).
const geometryCanvas = document.createElement('canvas');
geometryCanvas.width = 1;
geometryCanvas.height = 1;
const geometryCtx = geometryCanvas.getContext('2d')!;

export function isInside(path: Path2D, x: number, y: number): boolean {
  return geometryCtx.isPointInPath(path, x, y);
}

/** Converts a canvas pixel point into the vessel's local coordinate space. */
export function toLocalPoint(px: number, py: number, t: VesselTransform, bounds: VesselBounds): Point {
  return { x: (px - t.cx) / t.scale, y: (py - t.cy) / t.scale + bounds.midY };
}
