import { midpoint, type Vec2 } from "../core/geometry";
import { lighten, resolveHue, rgba } from "../core/palette";
import { MIN_RIBBON_WIDTH, metricsForSpeed } from "../core/ribbon-metrics";
import type { RibbonPoint, Stroke } from "../core/stroke";
import type { Ctx2D } from "./types";

/**
 * Which half of the ribbon a painter is responsible for.
 *
 * The body (pure hue) and the hot-core highlight (mixed toward white) live on
 * separate layers because the bloom is generated by blurring the body alone. If
 * the whitened highlight were part of the bloom source, the halo would come out
 * bleached instead of gold — measurably so: it drops the halo's saturation from
 * roughly 65% to under 40%, which is the artwork's whole identity (NFR-001.6).
 */
export type RibbonPass = "body" | "highlight";

export interface RibbonPaintOptions {
  /** Poster units → layer pixels. */
  readonly scale: number;
  /** Speed at which the width/glow mapping saturates. */
  readonly maxSpeed: number;
  /** Size of the layer this painter draws into, in layer pixels. */
  readonly width: number;
  readonly height: number;
  readonly pass: RibbonPass;
}

/**
 * The hot-core highlight: a near-white filament down the middle of the ribbon,
 * which is what gives a slow, thick stroke its neon-tube character.
 *
 * It can be pushed this far only because it lives on its own layer and never
 * feeds the bloom. Blurring a whitened core is what bleached the halo to grey in
 * an earlier revision (see {@link RibbonPass}).
 */
const HOT_CORE_MIX = 0.72;
const HOT_CORE_WIDTH_RATIO = 0.3;
const MIN_HOT_CORE_WIDTH = 1.2;
const HOT_CORE_ALPHA = 0.8;
const DOT_ALPHA = 0.85;

/**
 * Paints ribbons onto the *core* layer: plain variable-width strokes, no shadow
 * blur. Glow is produced afterwards by {@link BloomPipeline} from this layer as a
 * whole, which is what decouples cost from segment count (NFR-001.1).
 */
export class RibbonPainter {
  private options: RibbonPaintOptions;
  /** Next segment to commit: `segment` within `stroke`. Segment 0 is the lone-point dot. */
  private cursor = { stroke: 0, segment: 0 };

  constructor(
    private readonly ctx: Ctx2D,
    options: RibbonPaintOptions
  ) {
    this.options = options;
  }

  setOptions(options: RibbonPaintOptions): void {
    this.options = options;
  }

  /** Clears the layer and draws every stroke from scratch. */
  repaint(strokes: readonly Stroke[], isLastOpen = false): void {
    this.ctx.clearRect(0, 0, this.options.width, this.options.height);
    this.cursor = { stroke: 0, segment: 0 };
    this.appendPending(strokes, isLastOpen);
  }

  /**
   * Draws only the segments that have not been committed yet, leaving what is
   * already on the layer untouched. This is what keeps the cost of a drag
   * proportional to the points just added rather than to the whole artwork
   * (NFR-001.2).
   *
   * A segment is the arc centred on point `i`, so it can only be drawn once
   * point `i + 1` exists. While a stroke is still open its trailing segment is
   * therefore held back until the next point arrives, or until the stroke closes.
   */
  appendPending(strokes: readonly Stroke[], isLastOpen = false): void {
    this.prepare();

    for (let index = this.cursor.stroke; index < strokes.length; index++) {
      const stroke = strokes[index];
      if (!stroke) {
        continue;
      }

      const isOpen = isLastOpen && index === strokes.length - 1;
      const lastPoint = stroke.points.length - 1;
      const drawableTo = isOpen ? lastPoint - 1 : lastPoint;
      const from = index === this.cursor.stroke ? this.cursor.segment : 0;

      this.drawStroke(stroke, from, drawableTo);

      if (isOpen) {
        this.cursor = { stroke: index, segment: Math.max(from, drawableTo + 1) };
        return;
      }
      this.cursor = { stroke: index + 1, segment: 0 };
    }
  }

  protected prepare(): void {
    this.ctx.lineCap = "round";
    this.ctx.lineJoin = "round";
    /*
     * `source-over`, not `lighter`, *within* a layer.
     *
     * Consecutive segments overlap by a round cap at every joint. Adding them
     * clips the layer to near-white there, and since the bloom is a blur of this
     * layer, that clipping bleaches the halo — measured at rgb(32,30,19), only
     * 36% saturated, where the prototype's gold halo held 65%. Compositing the
     * finished layers onto the scene still uses `lighter`, so ribbons and their
     * glows continue to add together (FR-004.2).
     */
    this.ctx.globalCompositeOperation = "source-over";
  }

  /**
   * Draws segments `from`..`to` of a stroke, where segment `i` is the arc centred
   * on point `i`. Segment 0 is the lone-point dot.
   */
  protected drawStroke(stroke: Stroke, from: number, to: number): void {
    const { points } = stroke;
    const hex = resolveHue(stroke.colorId).hex;

    for (let i = from; i <= to; i++) {
      if (i === 0) {
        // A lone tap is a body-only mark; it has no highlight to speak of.
        if (points.length === 1 && this.options.pass === "body") {
          this.drawDot(points[0]!, hex);
        }
        continue;
      }
      const current = points[i];
      const previous = points[i - 1];
      if (!current || !previous) {
        continue;
      }
      const next = points[i + 1];
      const start = i === 1 ? previous : midpoint(previous, current);
      const end = next ? midpoint(current, next) : current;
      this.drawSegment(start, current, end, current.speed, hex);
    }
  }

  private drawSegment(
    start: Vec2,
    control: Vec2,
    end: Vec2,
    speed: number,
    hex: string
  ): void {
    const { scale, maxSpeed } = this.options;
    const metrics = metricsForSpeed(speed, maxSpeed);
    const ctx = this.ctx;

    ctx.beginPath();
    ctx.moveTo(start.x * scale, start.y * scale);
    ctx.quadraticCurveTo(control.x * scale, control.y * scale, end.x * scale, end.y * scale);

    if (this.options.pass === "body") {
      ctx.lineWidth = metrics.width * scale;
      ctx.strokeStyle = rgba(hex, metrics.alpha);
    } else {
      // The neon-tube highlight running down the middle of the ribbon.
      ctx.lineWidth = Math.max(MIN_HOT_CORE_WIDTH, metrics.width * HOT_CORE_WIDTH_RATIO) * scale;
      ctx.strokeStyle = rgba(
        lighten(hex, HOT_CORE_MIX),
        metrics.alpha * HOT_CORE_ALPHA * metrics.glow
      );
    }
    ctx.stroke();
  }

  private drawDot(point: RibbonPoint, hex: string): void {
    const { scale } = this.options;
    this.ctx.beginPath();
    this.ctx.fillStyle = rgba(hex, DOT_ALPHA);
    this.ctx.arc(point.x * scale, point.y * scale, (MIN_RIBBON_WIDTH / 2) * scale, 0, Math.PI * 2);
    this.ctx.fill();
  }
}
