import starsData from './data/stars.json';
import constellationsData from './data/constellations.json';
import type { ConstellationRecord, StarRecord } from './types';

/**
 * The static sky catalogue, generated by scripts/gen-catalog.mjs from the
 * Hipparcos-derived data bundled with d3-celestial (BSD-3-Clause, (c) Olaf
 * Frohn) and committed under src/data/. Nothing here is fetched at runtime.
 */
export const STARS: readonly StarRecord[] = starsData as StarRecord[];

export const CONSTELLATIONS: readonly ConstellationRecord[] =
  constellationsData as ConstellationRecord[];

/** The faintest magnitude the catalogue carries; shown in the poster legend. */
export const MAGNITUDE_LIMIT = 4.5;
